### ISSUE TITLE
provision-spec and provisioned-spec are not found in release 5.0.1.Final

### ISSUE THREAD

**Issue by michaelkimball** [wildfly/galleon#303]
When I use the galleon-5.0.1.Final release I am unable to get the `provision-spec` and `provisioned-spec` to work. I was able to install wildfly without a hitch, but I get an error that these commands are not found. The `install` and `pwd` commands are just to indicate that other commands are found. I'm running this in the `openjdk:17-slim-buster` docker image.
```sh
root@5bb8817a6788:~# galleon-5.0.1.Final/bin/galleon.sh 
[root]$ install
Error: Missing feature-pack
[root]$ pwd
/root
[root]$ provision-spec
Command named provision-spec was not found.
[root]$ provisioned-spec
Command named provisioned-spec was not found.
[root]$ provisioned-spec display --dir=/root/my-wildfly-server
Command named provisioned-spec display --dir=/root/my-wildfly-server was not found.
[root]$ ls
galleon-5.0.1.Final  galleon-5.0.1.Final.zip  my-wildfly-server  potato.xml
```

**Comment by jfdenise** [comment]
Hi Michael,
the galleon README is not accurate, I am going to fix it. Use 
"provision" command instead of "provision-spec", "get-info" instead of 
"provisioned-spec".
A source of documentation for galleon CLI tool is: 
https://docs.wildfly.org/galleon/#_galleon_cli_tool
Thank-you.
JF

**Comment by michaelkimball** [comment]
Thank you for you help and I am glad it is not a serious issue!
