### ISSUE TITLE
Make the capability of persisting hashes of a server public

### ISSUE THREAD

**Issue by gaol** [wildfly/galleon#325]
When working on https://github.com/wildfly-extras/prospero/issues/255, which needs a capability to generate hashes of the existing server installation without galleon metadata files, the hashes are needed for the comparison to the generated metadata files.

The hashes generation comes from: 
https://github.com/wildfly/galleon/blob/5.1.0.Final/core/src/main/java/org/jboss/galleon/ProvisioningManager.java#L831, and I think it would be good if we can reuse the capability in prospero.

So I propose to make `ProvisioningManager.persistHashes()` public, and change the parameter to the serverDir.

**Comment by jfdenise** [comment]
Could you log a JIRA issue against the GAL project?
In it could you provide a bit more context of what you want to achieve?
Thank-you.

**Comment by gaol** [comment]
The idea was to produce the `hashes` in an existing server without any galleon metadata files to compare with an galleon provisioned server, however, after discussion with @spyrkob , the changes may not be necessary anymore, using `FsEntryFactory.getInstance().filterGalleonPaths().forPath(serverDir)` can calculate the hashes, which is sufficient for the comparison, sorry for the noise. :)

**Comment by gaol** [comment]
close as won't fix
