### ISSUE TITLE
Missing `galleon-cli.jar` in the repository.

### ISSUE THREAD

**Issue by torsten-liermann** [wildfly/galleon#353]
Hi,

Please deploy all project artifacts again. I need the fat jar galleon-cli.jar in my Maven build. However, galleon-cli is missing for the current version. See here: [https://repository.jboss.org/nexus/content/groups/public/org/jboss/galleon/galleon-cli/](https://repository.jboss.org/nexus/content/groups/public/org/jboss/galleon/galleon-cli/)

https://groups.google.com/g/wildfly/c/0WWv6ca1Uok

Thanks,
Torsten

**Comment by jfdenise** [comment]
@torsten-liermann , fixed in 6.0.3.Final.
